// Code generated by protoc-gen-go. DO NOT EDIT.
// source: membership.proto

package membership

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type RequestMembership struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ReadOnly             int32    `protobuf:"varint,2,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestMembership) Reset()         { *m = RequestMembership{} }
func (m *RequestMembership) String() string { return proto.CompactTextString(m) }
func (*RequestMembership) ProtoMessage()    {}
func (*RequestMembership) Descriptor() ([]byte, []int) {
	return fileDescriptor_949fe0d019050ef5, []int{0}
}

func (m *RequestMembership) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestMembership.Unmarshal(m, b)
}
func (m *RequestMembership) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestMembership.Marshal(b, m, deterministic)
}
func (m *RequestMembership) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestMembership.Merge(m, src)
}
func (m *RequestMembership) XXX_Size() int {
	return xxx_messageInfo_RequestMembership.Size(m)
}
func (m *RequestMembership) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestMembership.DiscardUnknown(m)
}

var xxx_messageInfo_RequestMembership proto.InternalMessageInfo

func (m *RequestMembership) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RequestMembership) GetReadOnly() int32 {
	if m != nil {
		return m.ReadOnly
	}
	return 0
}

// The response message containing the greetings
type ReplyMembership struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyMembership) Reset()         { *m = ReplyMembership{} }
func (m *ReplyMembership) String() string { return proto.CompactTextString(m) }
func (*ReplyMembership) ProtoMessage()    {}
func (*ReplyMembership) Descriptor() ([]byte, []int) {
	return fileDescriptor_949fe0d019050ef5, []int{1}
}

func (m *ReplyMembership) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyMembership.Unmarshal(m, b)
}
func (m *ReplyMembership) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyMembership.Marshal(b, m, deterministic)
}
func (m *ReplyMembership) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyMembership.Merge(m, src)
}
func (m *ReplyMembership) XXX_Size() int {
	return xxx_messageInfo_ReplyMembership.Size(m)
}
func (m *ReplyMembership) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyMembership.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyMembership proto.InternalMessageInfo

func (m *ReplyMembership) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestMembership)(nil), "membership.request_membership")
	proto.RegisterType((*ReplyMembership)(nil), "membership.reply_membership")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MemRequestClient is the client API for MemRequest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MemRequestClient interface {
	SayHello(ctx context.Context, in *RequestMembership, opts ...grpc.CallOption) (*ReplyMembership, error)
}

type memRequestClient struct {
	cc *grpc.ClientConn
}

func NewMemRequestClient(cc *grpc.ClientConn) MemRequestClient {
	return &memRequestClient{cc}
}

func (c *memRequestClient) SayHello(ctx context.Context, in *RequestMembership, opts ...grpc.CallOption) (*ReplyMembership, error) {
	out := new(ReplyMembership)
	err := c.cc.Invoke(ctx, "/membership.MemRequest/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemRequestServer is the server API for MemRequest service.
type MemRequestServer interface {
	SayHello(context.Context, *RequestMembership) (*ReplyMembership, error)
}

func RegisterMemRequestServer(s *grpc.Server, srv MemRequestServer) {
	s.RegisterService(&_MemRequest_serviceDesc, srv)
}

func _MemRequest_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMembership)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemRequestServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/membership.MemRequest/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemRequestServer).SayHello(ctx, req.(*RequestMembership))
	}
	return interceptor(ctx, in, info, handler)
}

var _MemRequest_serviceDesc = grpc.ServiceDesc{
	ServiceName: "membership.MemRequest",
	HandlerType: (*MemRequestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _MemRequest_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "membership.proto",
}

func init() { proto.RegisterFile("membership.proto", fileDescriptor_949fe0d019050ef5) }

var fileDescriptor_949fe0d019050ef5 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0x4d, 0xcd, 0x4d,
	0x4a, 0x2d, 0x2a, 0xce, 0xc8, 0x2c, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0x88,
	0x28, 0xb9, 0x72, 0x09, 0x15, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0xc4, 0x23, 0x44, 0x85, 0x84,
	0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21,
	0x69, 0x2e, 0xce, 0xa2, 0xd4, 0xc4, 0x94, 0xf8, 0xfc, 0xbc, 0x9c, 0x4a, 0x09, 0x26, 0x05, 0x46,
	0x0d, 0xd6, 0x20, 0x0e, 0x90, 0x80, 0x7f, 0x5e, 0x4e, 0xa5, 0x92, 0x0e, 0x97, 0x40, 0x51, 0x6a,
	0x41, 0x4e, 0x25, 0xb2, 0x21, 0x12, 0x5c, 0xec, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0x30, 0x73,
	0x60, 0x5c, 0xa3, 0x08, 0x2e, 0x2e, 0xdf, 0xd4, 0xdc, 0x20, 0x88, 0xbd, 0x42, 0x5e, 0x5c, 0x1c,
	0xc1, 0x89, 0x95, 0x1e, 0xa9, 0x39, 0x39, 0xf9, 0x42, 0x72, 0x7a, 0x48, 0xae, 0xc5, 0x74, 0x98,
	0x94, 0x0c, 0xaa, 0x3c, 0xaa, 0x8d, 0x4a, 0x0c, 0x4e, 0x66, 0x5c, 0xd2, 0x99, 0xf9, 0x7a, 0xe9,
	0x45, 0x05, 0xc9, 0x7a, 0xa9, 0x15, 0x89, 0xb9, 0x05, 0x39, 0xa9, 0xc5, 0x48, 0x3a, 0x9c, 0xf8,
	0x7d, 0xe1, 0xec, 0x00, 0x50, 0x50, 0x04, 0x30, 0x2e, 0x62, 0x62, 0xf6, 0x75, 0xf5, 0x4d, 0x62,
	0x03, 0x87, 0x8c, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x3a, 0x4d, 0xb6, 0x23, 0x2d, 0x01, 0x00,
	0x00,
}
